### ISSUE TITLE
During the handling of a LIST request rood node is added to the children updates

### ISSUE THREAD

**Issue by tipok** [IOT-DSA/sdk-dslink-java#107]
We found following issue.
If the update is an array and the node is deleted, the root node is added to the updates which seems to be wrong in our understanding
https://github.com/IOT-DSA/sdk-dslink-java/blob/9c2aa044e35b72e4e0f4a75ec118b7c60c819001/sdk/dslink/src/main/java/org/dsa/iot/dslink/methods/responses/ListResponse.java#L186

**Comment by a-hansen** [comment]
Addressed in branch aaron180514:

https://github.com/IOT-DSA/sdk-dslink-java/compare/aaron180514
