### ISSUE TITLE
0.21.0 not available in Maven

### ISSUE THREAD

**Issue by mbreissi** [IOT-DSA/sdk-dslink-java#121]
The 0.21.0 release does not seem to be in the Maven repository.

**Comment by a-hansen** [comment]
Use 0.21.1 - https://mvnrepository.com/artifact/org.iot-dsa/dslink

**Comment by mbreissi** [comment]
Might want to create a tag label for that release.

**Comment by a-hansen** [comment]
Whoops, done.
