### ISSUE TITLE
Initial sensor values are not available

### ISSUE THREAD

**Issue by mpaatz** [IOT-DSA/sdk-dslink-java#39]
Hi,

If I list some nodes the initial sensor values for these nodes are not part of the ListResponse. Even after I subscribe to a node the update handler is never called if the values are more or less static.
For example if I import the Nodes at /downstream/System for most of the nodes the updateHandler is called after some time when the value changed. For nodes with static values like system platform this never happens. 
If I only subscribe to a single node (e.g. /downstream/System/Platform) it sometimes works.
Also sometimes it works if I do a reconnect and resubscribtion to the DgLux server.

Thanks

**Comment by kaendfinger** [comment]
@mpaatz Can you send us the code that you are using? It can be either privately on Slack or publicly here.

**Comment by mpaatz** [comment]
@kaendfinger I created a minimal code example but couldn't repdroduce the issue. After some debugging I found a timing issue somewhere in our data processing. So please close the bug as not a defect.

Thanks
