### ISSUE TITLE
Race condition for acquiring an NioEventLoopGroup object

### ISSUE THREAD

**Issue by huntc** [IOT-DSA/sdk-dslink-java#93]
If the event loop is called concurrently then there could be a race condition: https://github.com/IOT-DSA/sdk-dslink-java/blob/41091183ff122d967d3ae9123f64232034d0e347/internal/runtime_shared/src/main/java/org/dsa/iot/shared/SharedObjects.java#L36

**Comment by a-hansen** [comment]
The container runtime calls SDK Shared Objects methods from org.dsa.iot.container.Main.main function, hence from the main thread. SharedObjects is not changed after initialization by the main thread. Under these conditions no race condition can occur.

Furthermore the dslink SDK calls SharedObjects.getLoop() from org.dsa.iot.dslink.provider.netty.DefaultWsProvider.connect() and org.dsa.iot.dslink.provider.netty.DefaultHttpProvider.post(). Both invocations are non-concurrent from org.dsa.iot.dslink.connection.ConnectionManager.start(). There is also no obvious race condition

Whether the implementation is good is a completely different question.
