### ISSUE TITLE
POST requests should not block

### ISSUE THREAD

**Issue by huntc** [IOT-DSA/sdk-dslink-java#94]
Given the use of Netty, blocking should be avoided. I've noticed that POST requests block: https://github.com/IOT-DSA/sdk-dslink-java/blob/be834b55e17ada2355909a11e7951590277df049/sdk/dslink/src/main/java/org/dsa/iot/dslink/provider/netty/DefaultHttpProvider.java#L44

**Comment by a-hansen** [comment]
This is older code and the original implementer is no longer available.  We'd rather not fix something that isn't broken.

**Comment by huntc** [comment]
So the new code fixes the issue?
