### ISSUE TITLE
Query Regarding Invoke action

### ISSUE THREAD

**Issue by pra0909** [IOT-DSA/sdk-dslink-java#99]
Hi DSA Team,
I am using Java SDK to write an DSLink. I have a query regarding action on nodes. Suppose i have action_1 and other is action_2 . Now i want to invoke action_1 & when action_1 is invoked , it should invoke action_2. now problem is that i want to return result of action_2 from action_1. But it is not happening. So how can i implement this sync actions??

**Comment by Pacane** [comment]
I'm not sure I understand properly, but can you do this?

In your action_1 code:
- Get a requester reference
- Invoke action_2 from there
- In the action_2 response handler extract whatever you need from action_2's reponse
- Modify the action_1's ActionResult with what you need from action_2

**Comment by pra0909** [comment]
Yeah you got my point. I did same as you told, But when action_1 is invoked it's immediately come outside from action_1 handler, It is not waiting for invoke result of action_2.

**Comment by Pacane** [comment]
Can you show some code?

**Comment by pra0909** [comment]
private static void getSubscriptionInfo(Node node){
      LOGGER.info("------------ In get Subscription Info Action ------------------");
	  
      NodeBuilder builder = node.createChild(Constant.GETSUBINFO);
      builder.setSerializable(false);
      
	  builder.setAction(new Action(Permission.READ, new Handler<ActionResult>() {

          @Override
          public void handle(ActionResult event) {
              LOGGER.info("------------ In get Subscription Info Handler ------------------");

              try {

                 String action = "some other DSLink action node path";


                 String query = " db.restaurants.updateOne({'name' : 'Vella 2' },{ $set: {'violations' : 4}});";


                    InvokeRequest request = new InvokeRequest(action,new JsonObject().put("code",query));

                     ReqDSLink.getRequester().invoke(request, new Handler<InvokeResponse>() {
                        @Override
                        public void handle(InvokeResponse event) {
                        Table t = event.getTable();
                        LOGGER.info("total row is  :-"+t.getRows().size());
                        for(int i = 0; i < t.getRows().size(); i++) {
                            Value value  = new Value("");
                            Row row = t.getRows().get(i);
                            value = row.getValues().get(0);
                        }
                        }
                    });
              }catch (Exception e){
                  e.printStackTrace();
              }
    

              Table t = event.getTable();
              t.addColumn(new Parameter("fromGet",ValueType.STRING));
              t.addRow(Row.make(data.getValue()));

  LOGGER.info("\n*****************End Of get Handler **********\n");
          }

      }));
      builder.build();
  }

**Comment by Pacane** [comment]
so in your invoke part, that's where you want to process the action_1's result.

To do that, you want to get a reference on that event.table (from action_1) and use it in the invoke's handler.

Otherwise, yes, the code will not chain in the correct order.

In other words, the lines

```java
          Table t = event.getTable();
          t.addColumn(new Parameter("fromGet",ValueType.STRING));
          t.addRow(Row.make(data.getValue()));
```

should be placed after the `invoke` handler.

**Comment by pra0909** [comment]
Thanks for your solution. I tried it but again it's not waiting for invoke result. The flow reached end of handler(action_1) and then invoke (action_2 of other dslink) gets executed and not getting the response correspond to action_1. Can you please try the same scenario at your end????

**Comment by Pacane** [comment]
show me the new code please.

**Comment by pra0909** [comment]
ReqDSLink.getRequester().invoke(request, new Handler<InvokeResponse>() {
                        @Override
                        public void handle(InvokeResponse response) {
                            Table actioTable =  event.getTable();
                            actioTable.addColumn(new Parameter("Rsponse of getAction", ValueType.STRING));
                            Table t = response.getTable();
                        LOGGER.info("total row is  :-"+t.getRows().size());
                        for(int i = 0; i < t.getRows().size(); i++) {
                            Value value  = new Value("");
                            Row row = t.getRows().get(i);
                            value = row.getValues().get(0);
                            actioTable.addRow(Row.make(value));
                            LOGGER.info("Response of Mongo:- " + value.toString());
                        }
                        }
                    });

**Comment by Pacane** [comment]
and that doesn't work? If not, what does it do?

**Comment by pra0909** [comment]
yes, it is not working. The flow happens as follows:-

1.> First Action_1 handler executed.

2.> Then it invoke the action inside of action_1 handler.

3.> As soon as invoke request executed ; action_1 doesn't wait for invoke result and it completes it's task
and nothing return from action result.

4.> Then invoke is executed and store the retrieve data in action_1 table ; but now it is not useful now. 
and this end here.

**Comment by Pacane** [comment]
@d-shapiro got an idea of how to achieve this?

**Comment by mbreissi** [comment]
Action invocation is always asynchronous.  So in theory, in the inner invoke to action-2, you need to block the calling thread (in this case, the thread on which the action-1 handler is executing) until the handler for action-2 finishes.  Then you have the results from action-2 and can resume processing the handler for action-1.  Whether that actually works in the Java SDK, I don't know as I'm not well versed in the internal dispatch mechanism/thread assignments used by the Java SDK (i.e., blocking the processing of the action-1 response handler might prevent the response handler for action-2 being invoked).

**Comment by pra0909** [comment]
@mbreissi You mean i have to set wait state to "Action Result" handler  of action_1 thread, untill "Invoke Response" handler of action_2  Thread completed??

**Comment by mbreissi** [comment]
I think so if I am interpreting your first sentence correctly.  You need to make the call the to action_2 in your action_1 handler synchronous somehow.  There is no DSA/SDK support for synchronous invocation, so you need to do it yourself.  I usually do that by using a "SyncInvoker" class that does a busy wait until the response comes back.  It works well for simple cases.  

```
public class SyncInvoker implements Handler<InvokeResponse>
{
    private static final Logger LOGGER = LoggerFactory.getLogger(SyncInvoker.class);
    private InvokeResponse retVal = null;

    public InvokeResponse invoke(Requester requester, String pathToAction, JsonObject params, long timeoutMillis) throws TimeoutException
    {
        int rid = requester.invoke(new InvokeRequest(pathToAction, params), this);

        int waitMs = 0;
        while (retVal == null && waitMs < timeoutMillis)
        {
            try
            {
                sleep(1);
                waitMs++;
            }
            catch (InterruptedException e)
            {
                LOGGER.error("Invoke of " + pathToAction + " interrupted.", e);
            }
        }
        requester.closeStream(rid, null);

        if (waitMs >= timeoutMillis)
        {
            throw (new TimeoutException("Timeout attempting to invoke " + pathToAction));
        }

        return retVal;
    }

    @Override
    public void handle(InvokeResponse event)
    {
        this.retVal = event;
    }

    public static class TimeoutException extends IOException
    {
        public TimeoutException()
        {
            super();
        }

        public TimeoutException(String s)
        {
            super(s);
        }
    }
}
```

**Comment by pra0909** [comment]
Thanks @mbreissi , this is working for me now. Can i considered is as standard solution??

**Comment by mbreissi** [comment]
It's "standard" for me for simple use cases. I can't speak for the SDK owners however.

**Comment by pra0909** [comment]
Thanks @mbreissi @Pacane for help , above suggestions worked for me.
